# -*- coding: utf-8 -*-
"""assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l3G2HH96GEquizdePDDXNsdIGgHAK_LP
"""

import functools
import operator

list = [1,2,3,4,5]
print('sum of eliment is: ',end="")
print(functools.reduce(operator.add,list))

print('prodect of eliment is: ',end="")
print(functools.reduce(operator.mul,list))

l = [1,2,23,4,5,6,45,78,90,50]
x = filter(lambda x: x % 2 == 0, l)

print(l)

List = ['A', 'C', 'A', 'D', 'G', 'I', 'L', 'D']
print(List)
List1 = ['x', 'xx', 'xxx', 'y', 'yy', 'yyy', 'yyyy','z', 'zz', 'zzz', 'zzzz']
print(List1)
List2 = ['x', 'y', 'z', 'xx', 'yy', 'zz', 'xx', 'yy', 'zz', 'xxxx', 'yyyy', 'zzzz']
print(List2)
List3 = [[1], [2], [3], [4], [5], [6]]
print(List3)
List4 = [[2,3,4,5], [3,4,5,6], [4,5,6,7], [5,6,7,8]]
print(List4)
List5 = [(1,1), (2,1), (3,1), (1,2), (2,2), (3,2), (1,3), (2,3), (3,3)]
print(List5)

s = 20
a = 4
b = 7
c = 5

x = ((s*(s-a)*(s-b)*(s-c))**0.5)
print(x)

def long_words(n, str):
  word_len = []
  txt = str.split(" ")
  for x in txt:
    if len(x) > n:
      word_len.append(x)
  return word_len
print(long_words(2, "My name is Sandip Bnerjee"))